/**
 * Zod schema for event mutations (create + update).
 *
 * Mirrors `events` table columns per supabase/migrations/0001_events.sql.
 * `slug`, `year` are server-managed (slug from title, year generated by PG).
 */

import { z } from 'zod';

export const EventStatusEnum = z.enum(['upcoming', 'past', 'draft']);

export const EventInputSchema = z.object({
  title: z
    .string()
    .min(2, 'Title must be at least 2 characters')
    .max(200, 'Title must be at most 200 characters')
    .describe('Event title (required)'),
  subtitle: z
    .string()
    .max(300, 'Subtitle must be at most 300 characters')
    .nullish()
    .describe('Short tagline shown under the title'),
  description: z
    .string()
    .max(20000, 'Description must be at most 20,000 characters')
    .nullish()
    .describe('Markdown description of the event'),
  event_date: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/u, 'event_date must be ISO date YYYY-MM-DD')
    .describe('Primary event date (ISO YYYY-MM-DD)'),
  end_date: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/u, 'end_date must be ISO date YYYY-MM-DD')
    .nullish()
    .describe('End date for multi-day events (optional)'),
  venue_name: z
    .string()
    .max(200, 'Venue name must be at most 200 characters')
    .nullish()
    .describe('Venue display name'),
  venue_address: z
    .string()
    .max(500, 'Venue address must be at most 500 characters')
    .nullish()
    .describe('Street address'),
  venue_map_url: z
    .string()
    .url('venue_map_url must be a valid URL')
    .max(1000, 'venue_map_url must be at most 1000 characters')
    .nullish()
    .describe('Optional Google Maps share/embed URL'),
  poster_url: z
    .string()
    .url('poster_url must be a valid URL')
    .max(1000, 'poster_url must be at most 1000 characters')
    .nullish()
    .describe('Supabase Storage public URL of the poster image'),
  youtube_id: z
    .string()
    .regex(/^[A-Za-z0-9_-]{11}$/u, 'youtube_id must be an 11-char YouTube id')
    .nullish()
    .describe('YouTube video ID (11 chars)'),
  ticket_url: z
    .string()
    .url('ticket_url must be a valid URL')
    .max(1000, 'ticket_url must be at most 1000 characters')
    .nullish()
    .describe('External ticketing link'),
  ticket_cta: z
    .string()
    .min(1, 'ticket_cta cannot be empty')
    .max(50, 'ticket_cta must be at most 50 characters')
    .default('Get Tickets')
    .describe('Call-to-action text on the ticket button'),
  status: EventStatusEnum.describe("Event lifecycle status"),
  is_featured: z
    .boolean()
    .default(false)
    .describe('Feature on the home page'),
  collaborators: z
    .array(
      z
        .string()
        .min(1, 'Collaborator name cannot be empty')
        .max(200, 'Collaborator name must be at most 200 characters'),
    )
    .max(50, 'At most 50 collaborators allowed')
    .default([])
    .describe('List of collaborating organizations or artists'),
});

export type EventInput = z.infer<typeof EventInputSchema>;

/**
 * Partial schema for updates. Every field optional; we merge into existing row.
 * Use `.strict()` to reject unknown keys and avoid accidental column writes.
 */
export const EventUpdateSchema = EventInputSchema.partial();
export type EventUpdate = z.infer<typeof EventUpdateSchema>;

/**
 * YouTube video attachment input (event_videos table).
 */
export const EventVideoInputSchema = z.object({
  event_id: z.string().uuid('event_id must be a UUID').describe('Parent event UUID'),
  youtube_id: z
    .string()
    .regex(/^[A-Za-z0-9_-]{11}$/u, 'youtube_id must be an 11-char YouTube id')
    .describe('YouTube video ID (11 chars)'),
  title: z
    .string()
    .max(300, 'Title must be at most 300 characters')
    .nullish()
    .describe('Optional display title for the video'),
  sort_order: z
    .number()
    .int('sort_order must be an integer')
    .min(0, 'sort_order must be non-negative')
    .default(0)
    .describe('Display order (lower shows first)'),
});
export type EventVideoInput = z.infer<typeof EventVideoInputSchema>;
